@startuml
participant main.go
participant youtube.go
participant track.go.Play
participant track.go.audioroutine
participant track.go.getNextOpusFrame
participant opus.go

main.go -> youtube.go : NewYoutubeVideo()
main.go <- youtube.go : NewYoutubeVideo()
main.go -> track.go.Play : Play(track)
track.go.Play -> track.go.audioroutine : go audioroutine()
track.go.audioroutine -> opus.go : NewOpusEncoder()
track.go.audioroutine <- opus.go : NewOpusEncoder()
	loop
		track.go.audioroutine -> track.go.getNextOpusFrame : getNextOpusFrame(track, encoder)
		track.go.getNextOpusFrame -> youtube.go : track.GetPCMFrame(duration)
		track.go.getNextOpusFrame <- youtube.go : track.GetPCMFrame(duration)
		track.go.getNextOpusFrame -> opus.go : encoder.Encode(pcm)
		track.go.getNextOpusFrame <- opus.go : encoder:Encode(pcm)
		track.go.audioroutine <- track.go.getNextOpusFrame : getNextOpusFrame(track, encoder)
		track.go.audioroutine -> audiopackagewriter.go : sendAudioPacket(opusPayload)
		track.go.audioroutine <- audiopackagewriter.go : sendAudioPacket(opusPayload)
	end
main.go <- track.go.Play : Play(track)

@enduml
